spring:
  mvc:
    throw-exception-if-no-handler-found: true
  data:
    rest:
      base-path: /api
  datasource:
    url: 'jdbc:mariadb://localhost:3306/sowacustoms?verifyServerCertificate'
    username: root
    password:
    hikari:
      maximum-pool-size: '12'
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDB103Dialect
        format_sql: true
    hibernate:
      ddl-auto: update
  security:
    oauth2:
      client:
        registration:
          google:
            client-id:
            client-secret:
            redirect-uri: "{baseUrl}/oauth2/callback/{registrationId}"
            scope:
              - email
              - profile
  web:
    resources:
      add-mappings: false
app:
  tokenSecret: 926D96C90030DD58429D2751AC1BDBBC
  tokenExpirationMsec: 864000000
  rememberMeExpirationMsec: 7889400000
  authorizedRedirectUris:
    - http://localhost:3000/oauth2/redirect